on:
  push:
    branches:
      - test
  workflow_dispatch:

name: luci-app-clash

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      SDK_URL: https://downloads.openwrt.org/releases/23.05.5/targets/x86/64/openwrt-sdk-23.05.5-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz
      PKGN: luci-app-clash

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: src

      - name: Install dependencies
        run: |
          sudo apt-get -qq update
          sudo apt-get -y install \
            build-essential asciidoc binutils bzip2 gawk gettext git \
            libncurses5-dev libz-dev patch unzip zlib1g-dev \
            lib32gcc-s1 libc6-dev-i386 subversion gcc-multilib \
            libelf-dev autoconf automake libtool
          sudo apt-get -qq autoremove --purge
          sudo apt-get -qq clean

      - name: Download & extract SDK
        run: |
          wget -q "${SDK_URL}"
          tar xJf openwrt-sdk-*.tar.xz
          mv openwrt-sdk-* sdk

      - name: Prepare package
        run: |
          mv src sdk/package/${PKGN}

      - name: Prebuild po2lmo
        working-directory: sdk
        run: |
          if [ -d "package/${PKGN}/tools/po2lmo" ]; then
            pushd "package/${PKGN}/tools/po2lmo"
            make && sudo make install
            popd
          fi

      - name: Build
        working-directory: sdk
        run: |
          make defconfig
          make package/${PKGN}/compile -j$(nproc) V=s
          mkdir -p ../bin
          find bin/ -type f -name "*${PKGN}*" -exec cp -v {} ../bin/ \;

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ format('{0}-{1}', env.PKGN, github.sha) }}
          path: bin/
          retention-days: 7

